tasks:
  - name: Install Node.js dependencies
    init: bash setup.sh --install
  - name: Build docker image
    init: docker build -t blackcat:gitpod .

vscode:
  extensions:
    - enkia.tokyo-night
    - PKief.material-icon-theme
    - ms-azuretools.vscode-docker
