name: "🐛 回報漏洞"
description: 回報漏洞
body:
  - type: textarea
    id: current-behavior
    attributes:
      label: 目前行為
      description: 包括螢幕截圖、錯誤紀錄、審核日誌等的描述
      placeholder: 現在機器人...
    validations:
      required: true
      
  - type: textarea
    id: desired-behavior
    attributes:
      label: 預期行為
      description: 對於預期行為的詳細描述
      placeholder: 機器人應該...
    validations:
      required: true
      
  - type: textarea
    id: other
    attributes:
      label: 其他細節
      placeholder: 有任何其他細節嗎？
