name: "Code Scanning"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"

jobs:
  codeql:
    name: Code QL Scan
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: "javascript"
      - name: Setup node environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Run build
        run: |
          sudo apt install -y libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
          yarn install
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
  snyk:
    runs-on: ubuntu-latest
    name: Snyk Container Analysis

    steps:
      - uses: actions/checkout@v2
      - name: Build a Docker image
        run: docker build -t blackcat:snyk .
      - name: Run Snyk to check Docker image for vulnerabilities
        continue-on-error: true
        uses: snyk/actions/docker@14818c4695ecc4045f33c9cee9e795a788711ca4
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: blackcat:snyk
          args: --file=Dockerfile
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
